#!/usr/bin/python3

python_file="$PYFILE"

# Check if the file exists
if [ -f "$python_file" ]; then
    # Run the Python script
    python "$python_file"
else
    echo "Python file not found: $python_file"
fi
